## Put comments here that give an overall description of what your
## functions do

## The following function takes an invertible NxN matrix as an input and does the following:
## 1. creates a matrix object "inv" that can store itself into the cache; this object is the
##    inverse of the matrix fed to the new function.
## Note: the argument of "makeCacheMatrix" must be specified using the notation required by
## the "matrix" function (see ?matrix). For instance: makeCacheMatrix(matrix(i:j, N, N))

makeCacheMatrix <- function(x = matrix()) {
        
        # setting the inital values (matrix)
        
        inv <- NULL
        set <- function(y){
                x <<- y
                inv <<- NULL
        }
        
        # getting the value of the argument matrix
        
        get <- function() x
        
        # setting tha value of the inverse matrix
        
        setsolve <- function(solve) inv <<- solve
        
        # getting the value of the inverse matrix
        
        getsolve <- function() inv
        
        list(set=set, get=get, setsolve=setsolve, getsolve=getsolve)
}


## Our second function takes as arguemnt the output of the previous function (which
## is a special matrix) and does the following:
## 1. It searches the value of the cached inverse matrix "inv" throughout the object produced
##    by the previous function and checks its availability in the parent environment.
## 2. If there is already a cached inverse, the function returns that matrix (and a message).
## 3. If there is not a cached inverse, the function first retrieves the orginal
##    matrix, then it computes the inverse and stores it into the cache (by recalling
##    setsolve from the object generated by makeCacheMatrix. Finally the inverse is printed.

cacheSolve <- function(x, ...) {
        inv <- x$getsolve()
        if (!is.null(inv)) {
                message("getting chached matrix")
                return(inv)
        }
        else {
                matrix <- x$get()
                inv <- solve(matrix, ...)
                x$setsolve(inv)
                inv
        }
}


### TESTING ###

set.seed(1)

x <- matrix(rnorm(1:16),4,4)
solve(x)

rm(x)

set.seed(1)

cachematrix <- makeCacheMatrix(matrix(rnorm(1:16),4,4))
inv <- cacheSolve(cachematrix)
inv

inv2 <- cacheSolve(cachematrix)
inv2


